=== gentoo/gentoo-portage-rsync-mirror/metadata/dtd/metadata.dtd
<!ELEMENT packages ( pkgmetadata* )>

<!-- Metadata for a category -->
<!ELEMENT catmetadata ( (longdescription)* )>
<!ATTLIST catmetadata pkgname CDATA "">

<!-- Metadata for a package -->
<!ELEMENT pkgmetadata ( (herd|maintainer|natural-name|longdescription|use|upstream)* )>
<!ATTLIST pkgmetadata pkgname CDATA "">

  <!-- One tag for each herd this package is assigned to. -->
  <!ELEMENT herd (#PCDATA)>

  <!-- One tag for each maintainer of a package, multiple allowed-->
  <!ELEMENT maintainer ( email, (description| name)* )>

  <!-- Natural name for package, example: LibreOffice (for app-office/libreoffice) -->
  <!ELEMENT natural-name (#PCDATA) >

  <!-- A long description of the package in freetext-->
  <!ELEMENT longdescription (#PCDATA|pkg|cat)* >

  <!-- The changelog of the package-->
  <!-- Please note that #PCDATA is mentioned only for the upstream changelog
    element, where the content is a URL. This is due to limitations of the DTD -->
  <!ELEMENT changelog (#PCDATA|change)* >
    <!-- The changelog contains various "changes"-->
    <!ELEMENT change (date,(developer|version|description|file|contributor|bug)*) >
      <!ELEMENT date (#PCDATA) >
        <!-- The date of the change, in "YYYY-MM-DD" format -->
      <!ELEMENT developer (name?,email) >
        <!-- The developer that made the change. The email is required, name
	   is optional-->
      <!ELEMENT version (#PCDATA) >
        <!--version of the packages involved (one tag per version)-->
      <!ELEMENT file (#PCDATA) ><!-- one tag per file touched -->
      <!ELEMENT contributor (name?,email?) >
        <!-- A reference to a user that helped in causing this change. 
          There should at least be a name or email address included. 
          Email is preferred -->
      <!ELEMENT bug (#PCDATA) >
        <!-- bug-id of a bug fixed by this change, multiple allowed. The 
          format of this is a number or alias for a bug. NOT including a 
          # character -->

  <!-- description of what this USE flag does for this package -->
  <!ELEMENT use (flag)* >
    <!ELEMENT flag (#PCDATA|pkg|cat)* >
      <!-- name attribute holds the name of the USE flag -->
      <!ATTLIST flag name CDATA #REQUIRED >

  <!-- upstream metadata information (maintainers, upstream docs,..) -->
  <!ELEMENT upstream (maintainer|changelog|doc|bugs-to|remote-id)* >
    <!-- Due to the limitation of DTD this will also allow a status
      attribute for the package maintainer element. Please note that
      the usage of the status attribute is nevertheless _only_ allowed
      in the upstream maintainer element. -->
    <!ATTLIST maintainer status (active|inactive|unknown) "unknown" >
    <!-- URL where the location of the upstream documentation can be found -->
    <!ELEMENT doc (#PCDATA)>
      <!ATTLIST doc lang CDATA "C" >
    <!-- location where to report bugs
      (may also be an email address prefixed with mailto:) -->
    <!ELEMENT bugs-to (#PCDATA)>
    <!-- specify a type of package identification tracker -->
    <!ELEMENT remote-id (#PCDATA)>
      <!ATTLIST remote-id type (bitbucket|cpan|cpan-module|cpe|cran|ctan|freecode|freshmeat|github|gitorious|google-code|launchpad|pear|pecl|pypi|rubyforge|rubygems|sourceforge|sourceforge-jp|vim) #REQUIRED>

  <!-- category/package information for cross-linking in descriptions
    and useflag descriptions -->
  <!ELEMENT pkg (#PCDATA) >
  <!ELEMENT cat (#PCDATA) >
          
<!-- Common attributes -->

<!-- the lang attribute, specifies the language of this tag. This is 
  only useful for descriptions of various kinds. If a tag with this 
  attribute is included there must be a description in the default 
  language "C" or "en", which is equivalent -->
  <!ATTLIST description lang CDATA "C" >
  <!ATTLIST longdescription lang CDATA "C" >
  <!ATTLIST use lang CDATA "C" >

<!-- The restrict attribute, this attribute specifies restrictions on 
  the applicability of tags on versions. The format of this attribute is 
  equal to the format of DEPEND lines in ebuilds. There is one special 
  value though: restrict="*". A tag that specifies this only applies if 
  there are no other tags that apply.
  
  For required tags, there must be either an unrestricted version, or a 
  version that is default restricted. -->
  <!ATTLIST herd restrict CDATA #IMPLIED >
  <!ATTLIST maintainer restrict CDATA #IMPLIED >
  <!ATTLIST longdescription restrict CDATA #IMPLIED >
  <!ATTLIST flag restrict CDATA #IMPLIED >



<!-- standard parts -->
<!ELEMENT email (#PCDATA) ><!-- an email address -->
<!ELEMENT name (#PCDATA) ><!-- the name of a person (maintainer, contributor)-->
<!ELEMENT description (#PCDATA) ><!-- A description of a maintainer or change-->

=== gentoo/gentoo-portage-rsync-mirror/dev-qt/qthelp/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
	<herd>qt</herd>
	<use>
		<flag name="compat">Build the extra compatibility layer required by a few packages, see
			http://blog.qt.digia.com/blog/2010/06/22/qt-assistant-compat-version-available-as-extra-source-package/</flag>
		<flag name="exceptions">Add support for exceptions - like catching them
			inside the event loop (recommended by upstream)</flag>
	</use>
	<upstream>
		<bugs-to>https://bugreports.qt.io/</bugs-to>
		<doc>http://qt-project.org/doc/</doc>
	</upstream>
</pkgmetadata>

=== gentoo/gentoo-portage-rsync-mirror/app-admin/ansible/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
  <maintainer>
    <email>pinkbyte@gentoo.org</email>
    <name>Sergey Popov</name>
  </maintainer>
  <maintainer>
    <email>jlec@gentoo.org</email>
    <name>Justin Lecher</name>
  </maintainer>
  <upstream>
    <remote-id type="github">ansible/ansible</remote-id>
    <bugs-to>https://github.com/ansible/ansible/issues</bugs-to>
  </upstream>
  <longdescription lang="en">
Radically simple deployment, model-driven configuration management, and 
command execution framework.
</longdescription>
</pkgmetadata>

=== gentoo/gentoo-portage-rsync-mirror/app-admin/testdisk/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
    <herd>forensics</herd>
    <maintainer>
        <email>robbat2@gentoo.org</email>
		<name>Robin H. Johnson</name>
		<description>Primary maintainer</description>
    </maintainer>
	<use>
		<flag name='ntfs'>Include the ability to read NTFS filesystems</flag>
		<flag name='reiserfs'>include reiserfs reading ability</flag>
	</use>
</pkgmetadata>

=== gentoo/gentoo-portage-rsync-mirror/sci-biology/GBrowse/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
  <herd>sci</herd>
  <herd>perl</herd>
  <maintainer>
    <email>weaver@gentoo.org</email>
    <name>Andrey Kislyuk</name>
  </maintainer>
  <upstream>
    <remote-id type="cpan">GBrowse</remote-id>
  </upstream>
</pkgmetadata>

=== gentoo/gentoo-portage-rsync-mirror/dev-libs/uchardet/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
	<herd>proxy-maintainers</herd>
	<maintainer>
		<email>rion4ik@gmail.com</email>
		<name>Rion</name>
	</maintainer>
	<maintainer>
		<email>nikoli@gmx.us</email>
		<name>Nikoli</name>
	</maintainer>
</pkgmetadata>

=== gentoo/gentoo-portage-rsync-mirror/dev-python/django-tastypie/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
	<maintainer>
		<email>idella4@gentoo.org</email>
		<name>Ian Delaney</name>
	</maintainer>
	<herd>python</herd>
	<use>
		<flag name='bip'>An optional serialiser dev-python/biplist</flag>
		<flag name='digest'>Library to aid in implementing HTTP Digest Authentication</flag>
		<flag name='lxml'>An optional serialiser dev-python/lxml</flag>
		<flag name='oauth'>Adds OAuth authentication support</flag>
		<flag name='yaml'>An optional serialiser dev-python/yaml</flag>
	</use>
</pkgmetadata>

=== gentoo/gentoo-portage-rsync-mirror/gnome-base/gdm/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
<herd>gnome</herd>
<use>
	<flag name="audit">Enable support for <pkg>sys-process/audit</pkg></flag>
	<flag name="fprint">Enables experimental fingerprint authentication using
		<pkg>sys-auth/fprintd</pkg></flag>
	<flag name="plymouth">Enable support for smooth transition from
		<pkg>sys-boot/plymouth</pkg></flag>
</use>
</pkgmetadata>

=== gentoo/gentoo-portage-rsync-mirror/x11-misc/x11vnc/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
	<herd>proxy-maintainers</herd>
	<maintainer>
		<email>alex_y_xu@yahoo.ca</email>
		<name>Alex Xu</name>
		<description>Proxy maintainer. CC him on bugs</description>
	</maintainer>
	<longdescription>
		The primary goal of this program is to create a portable and
		simple command-line server utility that allows a VNC viewer
		to connect to an actual X display.
	</longdescription>
	<use>
		<flag name="system-libvncserver">Build x11vnc against the system
			libvncserver (experimental)</flag>
		<flag name="tk">Support the simple tcl/tk -gui option</flag>
	</use>
</pkgmetadata>
