=== gentoo/gentoo-portage-rsync-mirror/metadata/dtd/metadata.dtd
<!ELEMENT packages ( pkgmetadata* )>

<!-- Metadata for a category -->
<!ELEMENT catmetadata ( (longdescription)* )>
<!ATTLIST catmetadata pkgname CDATA "">

<!-- Metadata for a package -->
<!ELEMENT pkgmetadata ( (herd|maintainer|natural-name|longdescription|use|upstream)* )>
<!ATTLIST pkgmetadata pkgname CDATA "">

  <!-- One tag for each herd this package is assigned to. -->
  <!ELEMENT herd (#PCDATA)>

  <!-- One tag for each maintainer of a package, multiple allowed-->
  <!ELEMENT maintainer ( email, (description| name)* )>

  <!-- Natural name for package, example: LibreOffice (for app-office/libreoffice) -->
  <!ELEMENT natural-name (#PCDATA) >

  <!-- A long description of the package in freetext-->
  <!ELEMENT longdescription (#PCDATA|pkg|cat)* >

  <!-- The changelog of the package-->
  <!-- Please note that #PCDATA is mentioned only for the upstream changelog
    element, where the content is a URL. This is due to limitations of the DTD -->
  <!ELEMENT changelog (#PCDATA|change)* >
    <!-- The changelog contains various "changes"-->
    <!ELEMENT change (date,(developer|version|description|file|contributor|bug)*) >
      <!ELEMENT date (#PCDATA) >
        <!-- The date of the change, in "YYYY-MM-DD" format -->
      <!ELEMENT developer (name?,email) >
        <!-- The developer that made the change. The email is required, name
	   is optional-->
      <!ELEMENT version (#PCDATA) >
        <!--version of the packages involved (one tag per version)-->
      <!ELEMENT file (#PCDATA) ><!-- one tag per file touched -->
      <!ELEMENT contributor (name?,email?) >
        <!-- A reference to a user that helped in causing this change. 
          There should at least be a name or email address included. 
          Email is preferred -->
      <!ELEMENT bug (#PCDATA) >
        <!-- bug-id of a bug fixed by this change, multiple allowed. The 
          format of this is a number or alias for a bug. NOT including a 
          # character -->

  <!-- description of what this USE flag does for this package -->
  <!ELEMENT use (flag)* >
    <!ELEMENT flag (#PCDATA|pkg|cat)* >
      <!-- name attribute holds the name of the USE flag -->
      <!ATTLIST flag name CDATA #REQUIRED >

  <!-- upstream metadata information (maintainers, upstream docs,..) -->
  <!ELEMENT upstream (maintainer|changelog|doc|bugs-to|remote-id)* >
    <!-- Due to the limitation of DTD this will also allow a status
      attribute for the package maintainer element. Please note that
      the usage of the status attribute is nevertheless _only_ allowed
      in the upstream maintainer element. -->
    <!ATTLIST maintainer status (active|inactive|unknown) "unknown" >
    <!-- URL where the location of the upstream documentation can be found -->
    <!ELEMENT doc (#PCDATA)>
      <!ATTLIST doc lang CDATA "C" >
    <!-- location where to report bugs
      (may also be an email address prefixed with mailto:) -->
    <!ELEMENT bugs-to (#PCDATA)>
    <!-- specify a type of package identification tracker -->
    <!ELEMENT remote-id (#PCDATA)>
      <!ATTLIST remote-id type (bitbucket|cpan|cpan-module|cpe|cran|ctan|freecode|freshmeat|github|gitorious|google-code|launchpad|pear|pecl|pypi|rubyforge|rubygems|sourceforge|sourceforge-jp|vim) #REQUIRED>

  <!-- category/package information for cross-linking in descriptions
    and useflag descriptions -->
  <!ELEMENT pkg (#PCDATA) >
  <!ELEMENT cat (#PCDATA) >
          
<!-- Common attributes -->

<!-- the lang attribute, specifies the language of this tag. This is 
  only useful for descriptions of various kinds. If a tag with this 
  attribute is included there must be a description in the default 
  language "C" or "en", which is equivalent -->
  <!ATTLIST description lang CDATA "C" >
  <!ATTLIST longdescription lang CDATA "C" >
  <!ATTLIST use lang CDATA "C" >

<!-- The restrict attribute, this attribute specifies restrictions on 
  the applicability of tags on versions. The format of this attribute is 
  equal to the format of DEPEND lines in ebuilds. There is one special 
  value though: restrict="*". A tag that specifies this only applies if 
  there are no other tags that apply.
  
  For required tags, there must be either an unrestricted version, or a 
  version that is default restricted. -->
  <!ATTLIST herd restrict CDATA #IMPLIED >
  <!ATTLIST maintainer restrict CDATA #IMPLIED >
  <!ATTLIST longdescription restrict CDATA #IMPLIED >
  <!ATTLIST flag restrict CDATA #IMPLIED >



<!-- standard parts -->
<!ELEMENT email (#PCDATA) ><!-- an email address -->
<!ELEMENT name (#PCDATA) ><!-- the name of a person (maintainer, contributor)-->
<!ELEMENT description (#PCDATA) ><!-- A description of a maintainer or change-->

=== gentoo/gentoo-portage-rsync-mirror/media-sound/mp3splt-gtk/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
	<herd>sound</herd>
	<maintainer>
		<email>sping@gentoo.org</email>
		<name>Sebastian Pipping</name>
	</maintainer>
	<use>
		<flag name='audacious'>Include <pkg>media-sound/audacious</pkg> support</flag>
		<flag name='gtk3'>Link against <pkg>x11-libs/gtk+</pkg>:3 instead of <pkg>x11-libs/gtk+</pkg>:2</flag>
	</use>
</pkgmetadata>

=== gentoo/gentoo-portage-rsync-mirror/net-misc/vpnc/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
  <herd>proxy-maintainers</herd>
  <maintainer>
    <email>ljakab@ac.upc.edu</email>
    <name>Lor√°nd Jakab</name>
  </maintainer>
  <maintainer>
    <email>mmokrejs@gmail.com</email>
    <name>Martin Mokrejs</name>
  </maintainer>
  <maintainer>
    <email>jlec@gentoo.org</email>
    <name>Justin Lecher</name>
  </maintainer>
  <use>
    <flag name="resolvconf">Enable support for DNS managing framework <pkg>net-dns/openresolv</pkg></flag>
  </use>
</pkgmetadata>

=== gentoo/gentoo-portage-rsync-mirror/x11-terms/xterm/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
  <maintainer>
    <email>dickey@invisible-island.net</email>
    <name>Thomas Dickey</name>
  </maintainer>
  <herd>x11</herd>
  <herd>proxy-maintainers</herd>
  <use>
    <flag name="openpty">Use openpty() in preference to posix_openpt()</flag>
    <flag name="toolbar">Enable the xterm toolbar to be built</flag>
  </use>
</pkgmetadata>

=== gentoo/gentoo-portage-rsync-mirror/net-libs/libnids/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
<herd>netmon</herd>
<longdescription>emulates the IP stack of Linux 2.0.x and offers IP defragmentation, TCP stream assembly and TCP port scan detection.</longdescription>
<use>
<flag name="glib">Use <pkg>dev-libs/glib</pkg> for multiprocessing support</flag>
<flag name="libnet">Include code requiring <pkg>net-libs/libnet</pkg></flag>
</use>
</pkgmetadata>

=== gentoo/gentoo-portage-rsync-mirror/sci-chemistry/icm/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
	<herd>sci-chemistry</herd>
	<maintainer>
		<email>alexxy@gentoo.org</email>
		<name>Alexey Shvetsov</name>
	</maintainer>
	<use>
		<flag name="32bit">Automatically generated description for 32bit</flag>
		<flag name="64bit">Automatically generated description for 64bit</flag>
	</use>
</pkgmetadata>

=== gentoo/gentoo-portage-rsync-mirror/media-sound/audacity/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
	<herd>proaudio</herd>
	<maintainer>
		<email>richard@audacityteam.org</email>
		<name>Richard Ash</name>
		<description>Upstream - please CC on bugs that concerns upstream</description>
	</maintainer>
	<use>
		<flag name="id3tag">Enables ID3 tagging with id3tag library</flag>
		<flag name="libsoxr">Uses <pkg>media-libs/soxr</pkg> as audio resampling library: Better quality than the included resampler and much faster than libsamplerate while keeping almost the same quality.</flag>
		<flag name="midi">Enables MIDI support</flag>
		<flag name="sbsms">Enables sbsms library support for pitch and tempo changing</flag>
		<flag name="soundtouch">Enables soundtouch library support for pitch and tempo changing</flag>
		<flag name="twolame">Enables twolame support (MPEG Audio Layer 2 encoder)</flag>
		<flag name="vamp">Enables vamp plugins support (Audio analysing plugins)</flag>
	</use>
	<upstream>
		<remote-id type="google-code">audacity</remote-id>
	</upstream>
</pkgmetadata>

=== gentoo/gentoo-portage-rsync-mirror/media-libs/freetype/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
	<herd>fonts</herd>
	<maintainer>
		<email>yngwin@gentoo.org</email>
		<name>Ben de Groot</name>
	</maintainer>
	<maintainer>
		<email>multilib@gentoo.org</email>
		<name>gx86-multilib project</name>
		<description>Handling the bugs related to multilib support in the package and related changes.</description>
	</maintainer>
	<use>
		<flag name="auto-hinter">Use the unpatented auto-hinter instead
			of the (recommended) TrueType bytecode interpreter</flag>
		<flag name="bzip2">Support bzip2 compressed PCF fonts.</flag>
		<flag name="fontforge">Install internal headers required for TrueType
			debugger in <pkg>media-gfx/fontforge</pkg> (built with
			USE=truetype-debugger)</flag>
		<flag name="infinality">Enable infinality options for improved LCD
			filtering</flag>
		<flag name="utils">Install utilities and examples from ft2demos</flag>
	</use>
</pkgmetadata>

=== gentoo/gentoo-portage-rsync-mirror/dev-perl/DateTime-Set/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
  <herd>perl</herd>
  <upstream>
    <remote-id type="cpan">DateTime-Set</remote-id>
    <remote-id type="cpan-module">DateTime::Set</remote-id>
    <remote-id type="cpan-module">DateTime::Span</remote-id>
    <remote-id type="cpan-module">DateTime::SpanSet</remote-id>
    <remote-id type="cpan-module">Set::Infinite::_recurrence</remote-id>
  </upstream>
</pkgmetadata>
